<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="EPPlus" Version="7.1.1" />
    <PackageReference Include="QuestPDF" Version="2025.7.2" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Hospital.Entities\Hospital.Entities.csproj" />
    <ProjectReference Include="..\Hospital.Interfaces\Hospital.Interfaces.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="ExcelTemplate\" />
    <Folder Include="PdfTemplate\" />
  </ItemGroup>

</Project>
